### Проверка сервера
GET http://localhost:3000 HTTP/1.1

### Получить всех пользователей
GET http://localhost:3000/api/users HTTP/1.1

### Создать пользователя
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Мария Сидорова",
  "email": "maria@example.com",
  "age": 32
}

### Получить пользователя по ID
GET http://localhost:3000/api/users/1 HTTP/1.1

### Обновить пользователя
PUT http://localhost:3000/api/users/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Мария Обновленная",
  "email": "maria.new@example.com",
  "age": 33
}

### Удалить пользователя
DELETE http://localhost:3000/api/users/1 HTTP/1.1